# Generated by Django 3.1 on 2021-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210609_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
    ]
